[window]
# Higher opacity (0.8) ensures readability on white backgrounds
opacity = 0.60
blur = true
padding = { x = 12, y = 12 }


[font]
size = 16

[cursor]
style = { shape = "Block", blinking = "Off" }




[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"
# ------------------------------------------
#       MATTE MANGA (CUSTOM PALETTE)
# ------------------------------------------

[colors.primary]
background = "#121212" # Your Matte Black
foreground = "#bebebe" # Your Matte Grey

[colors.cursor]
text = "#121212"
cursor = "#eaeaea"

[colors.selection]
text = "#bebebe"
background = "#333333"

[colors.normal]
black   = "#333333"
red     = "#D35F5F" # Muted Red
green   = "#FFC107" # Amber/Gold
yellow  = "#b91c1c" # Blood Red
blue    = "#e68e0d" # Your Accent Orange
magenta = "#D35F5F"
cyan    = "#bebebe"
white   = "#bebebe"

[colors.bright]
black   = "#8a8a8d"
red     = "#B91C1C"
green   = "#FFC107"
yellow  = "#b90a0a"
blue    = "#f59e0b"
magenta = "#B91C1C"
cyan    = "#eaeaea"
white   = "#ffffff"
